Repository CS2113-AY1819S1-W12-1/main, pull requests merged in 2018-11, with the labels that each got.

#142 Attempt to fix coveralls
  README.adoc
Labels: priority.medium, severity.Low

#143 Jitwei98/reposense
  .gitignore
  _reposense/config.json
Labels: priority.high, type.task

#174 Suggestion Improvement
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/elstonayx.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExportAllCommand.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/TodoCommand.java
  src/main/java/seedu/address/logic/suggestions/InputCommandSuggestion.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/seedu/address/logic/suggestions/InputCommandSuggestionTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
Labels: status.ongoing

#179 Add link to code contributed
  docs/team/jitwei98.adoc
Labels: priority.low

#181 Remove todo from import/export
  src/main/java/seedu/address/export/Export.java
  src/main/java/seedu/address/export/ExportManager.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/TodoCommandTest.java
Labels: priority.medium

#183 Hardcode calendar
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/calendar/MonthView.java
  src/main/resources/images/welcome.png
  src/main/resources/view/CalendarPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MonthView.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/TodoListCard.fxml
Labels: priority.high

#187 Remove badges from AB4
  README.adoc
Labels: priority.medium

#192 elstonayx/Personal Project Portfolio
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/InputCommandSuggestionSequenceDiagram.pptx
  docs/diagrams/WrongCommandSuggestionSequenceDiagram.pptx
  docs/images/InputCommandSuggestionSequenceDiagram.png
  docs/images/WrongCommandSuggestionSequenceDiagram.png
  docs/images/elstonayx.png
  docs/team/elstonayx.adoc
  src/main/java/seedu/address/logic/suggestions/StringSimilarity.java
  src/main/java/seedu/address/logic/suggestions/WrongCommandSuggestion.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: status.ongoing

#188 All commands completed, pushing present test cases first for merge
  .gitignore
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/PersonPanelSelectionChangedEvent.java
  src/main/java/seedu/address/logic/commands/ClearScheduleCommand.java
  src/main/java/seedu/address/logic/commands/MatchScheduleCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClearScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/MatchScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/model/person/Schedule.java
  src/main/java/seedu/address/model/person/TheDate.java
  src/main/java/seedu/address/model/person/Time.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/storage/XmlAdaptedSchedule.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/CalendarBackground.html
  src/main/resources/view/CalendarPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/default.html
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/ResultDisplayTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: priority.high

#210 Minor modifications
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ExportComponentClassDiagram.pptx
  docs/diagrams/ImportComponentClassDiagram.pptx
  docs/images/ExportClassDiagram.png
  docs/images/ImportClassDiagram.png
  docs/images/exportAlex.png
  docs/images/findAlex.png
  docs/team/jitwei98.adoc
  src/main/java/seedu/address/export/CsvWriter.java
  src/main/java/seedu/address/export/Export.java
  src/main/java/seedu/address/export/ImportManager.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/suggestions/InputCommandSuggestion.java
  src/main/java/seedu/address/model/UserPrefs.java
Labels: priority.high
