Repository CS2113-AY1819S1-W12-1/main, pull requests merged in 2018-10, with the labels that each got.

#32 Jitwei98/exportall command
  src/main/java/seedu/address/logic/commands/ExportAllCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ExportAllCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/ExportAllCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ExportAllCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalFiletypes.java
Labels: priority.medium

#42 Jitwei98/convert images to png
  docs/AboutUs.adoc
  docs/images/driedmelon.jpg
  docs/images/driedmelon.png
  docs/images/elstonayx.jpg
  docs/images/elstonayx.png
  docs/images/jitwei98.jpg
  docs/images/jitwei98.png
  docs/images/junweiljw.jpg
  docs/images/junweiljw.png
  docs/images/linnnruoo.jpg
  docs/images/linnnruoo.png
Labels: priority.medium

#57 added LMGTFY
  src/main/java/seedu/address/ui/BrowserPanel.java
Labels: priority.medium, type.enhancement

#62 Write to .csv file
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/export/CsvWriter.java
  src/main/java/seedu/address/export/Export.java
  src/main/java/seedu/address/export/ExportManager.java
  src/main/java/seedu/address/logic/commands/ExportAllCommand.java
  src/main/java/seedu/address/model/Filetype.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/sandboxmanyPersons.xml
  src/test/java/seedu/address/export/CsvWriterTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ExportAllCommandTest.java
  src/test/java/seedu/address/model/FiletypeTest.java
Labels: priority.high, type.task

#72 Jitwei98/docs v1.2
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ExportAllSequenceDiagram.png
Labels: priority.high, status.ongoing

#79 Updated UGDG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.medium, status.ongoing

#102 Jitwei98/filetype class
  src/main/java/seedu/address/logic/commands/ExportAllCommand.java
  src/main/java/seedu/address/logic/parser/ExportAllCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/ExportAllCommandTest.java
  src/test/java/seedu/address/logic/parser/ExportAllCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.medium, type.task

#104 Minor refactoring
  src/main/java/seedu/address/export/CsvWriter.java
  src/main/java/seedu/address/model/Filetype.java
  src/test/java/seedu/address/export/CsvWriterTest.java
Labels: priority.low

#108 Check if the file path exists before writing to the file
  src/main/java/seedu/address/export/CsvWriter.java
  src/main/java/seedu/address/logic/commands/ExportAllCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.high, type.bug

#117 Jitwei98/ui component
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/guitests/guihandles/StatusBarFooterHandle.java
  src/test/java/seedu/address/ui/StatusBarFooterTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
Labels: priority.medium, type.enhancement

#119 Add test cases for todo task
  src/main/java/seedu/address/ui/TodoListPanel.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/TodoCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/TodoCommandTest.java
  src/test/java/seedu/address/logic/parser/TodoCommandParserTest.java
  src/test/java/seedu/address/model/todo/ContentTest.java
  src/test/java/seedu/address/model/todo/TitleTest.java
  src/test/java/seedu/address/model/todo/TodoTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TodoBuilder.java
  src/test/java/seedu/address/testutil/TodoUtil.java
  src/test/java/seedu/address/testutil/TypicalTodos.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/TodoCommandSystemTest.java
Labels: priority.high

#111 Filetype.java: Modify headers for various methods
  src/main/java/seedu/address/model/Filetype.java
Labels: priority.low

#109 Elstonayx/suggest corrections
  docs/team/elstonayx.adoc
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/suggestions/InputCommandSuggestion.java
  src/main/java/seedu/address/logic/suggestions/StringSimilarity.java
  src/main/java/seedu/address/logic/suggestions/Trie.java
  src/main/java/seedu/address/logic/suggestions/WrongCommandSuggestion.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/logic/CommandSuggestionTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/suggestions/InputCommandSuggestionTest.java
  src/test/java/seedu/address/logic/suggestions/StringSimilarityTest.java
  src/test/java/seedu/address/logic/suggestions/TrieTest.java
  src/test/java/seedu/address/logic/suggestions/WrongCommandSuggestionTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
  src/test/java/systemtests/TodoCommandSystemTest.java
Labels: status.ongoing

#113 Export v1.3 (without docs)
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/export/CsvWriter.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/java/seedu/address/export/CsvWriterTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/TodoCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ExportAllCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
Labels: priority.high, type.enhancement

#127 Modify User Guide
  docs/UserGuide.adoc
Labels: priority.high

#123 Able to add schedule to person, cannot delete schedule
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Date.java
  src/main/java/seedu/address/model/person/EventName.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Schedule.java
  src/main/java/seedu/address/model/person/Time.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/storage/XmlAdaptedSchedule.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
Labels: priority.high, status.ongoing, type.epic
